name: "Standard"

run-name: ${{ github.run_number }} [${{ github.actor }}] on ${{ github.ref_name }}

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *' # Once a day at 12am UTC
  workflow_dispatch:

permissions: {}

jobs:
  # ----------------------------------------------------------------------
  action_contexts:
    name: "Display GitHub Action Contexts"
    uses: davidbrownell/dbrownell_DevTools/.github/workflows/callable_display_action_contexts.yaml@CI-v0.22.1

  # ----------------------------------------------------------------------
  validate:
    strategy:
      fail-fast: false

      matrix:
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest

        python_version:
          - "3.12"
          - "3.11"
          - "3.10"
          # - "3.9"  # Not supported
          # - "3.8"  # Not supported

    name: Validate

    permissions:
      contents: read

    uses: davidbrownell/dbrownell_DevTools/.github/workflows/callable_validate_python.yaml@CI-v0.22.1
    with:
      operating_system: ${{ matrix.os }}
      python_version: ${{ matrix.python_version }}

  # ----------------------------------------------------------------------
  package_coverage:
    needs: validate

    name: Postprocess Coverage Info

    permissions:
      contents: read

    uses: davidbrownell/dbrownell_DevTools/.github/workflows/callable_package_python_coverage.yaml@CI-v0.22.1
    with:
      gist_id: f15146b1b8fdc0a5d45ac0eb786a84f7
      gist_filename: FileBackup_coverage.json
    secrets:
      GIST_TOKEN: ${{ secrets.GIST_TOKEN }}

  # ----------------------------------------------------------------------
  create_package:
    needs: package_coverage

    strategy:
      fail-fast: false

      matrix:
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest

        python_version:
          - "3.12"
          - "3.11"
          - "3.10"
          # - "3.9"  # Not supported
          # - "3.8"  # Not supported

    name: Create Package

    permissions:
      contents: read

    uses: davidbrownell/dbrownell_DevTools/.github/workflows/callable_create_python_package.yaml@CI-v0.22.1
    with:
      operating_system: ${{ matrix.os }}
      python_version: ${{ matrix.python_version }}

  # ----------------------------------------------------------------------
  validate_package:
    needs: create_package

    strategy:
      fail-fast: false

      matrix:
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest

        python_version:
          - "3.12"
          - "3.11"
          - "3.10"
          # - "3.9"  # Not supported
          # - "3.8"  # Not supported

    name: Validate Package

    permissions:
      contents: read

    uses: davidbrownell/dbrownell_DevTools/.github/workflows/callable_validate_python_package.yaml@CI-v0.22.1
    with:
      operating_system: ${{ matrix.os }}
      python_version: ${{ matrix.python_version }}
      validation_command: python -c "from FileBackup import __version__; print(__version__)"

  # ----------------------------------------------------------------------
  create_binary:
    needs: package_coverage

    strategy:
      fail-fast: false

      matrix:
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest

        python_version:
          - "3.11"

    name: Create Binary

    permissions:
      contents: read

    uses: davidbrownell/dbrownell_DevTools/.github/workflows/callable_create_python_binary.yaml@CI-v0.22.1
    with:
      operating_system: ${{ matrix.os }}
      python_version: ${{ matrix.python_version }}

  # ----------------------------------------------------------------------
  validate_binary:
    needs: create_binary

    strategy:
      fail-fast: false

      matrix:
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest

        python_version:
          - "3.11"

    name: Validate Binary

    permissions:
      contents: read

    uses: davidbrownell/dbrownell_DevTools/.github/workflows/callable_validate_python_binary.yaml@CI-v0.22.1
    with:
      operating_system: ${{ matrix.os }}
      python_version: ${{ matrix.python_version }}
      validation_command: FileBackup version


  # ----------------------------------------------------------------------
  create_docker_image:
    needs: package_coverage

    strategy:
      fail-fast: false

      matrix:
        python_version:
          - "3.12"
          - "3.11"
          - "3.10"
          # - "3.9"  # Not supported
          # - "3.8"  # Not supported

    name: Create Docker Image

    permissions:
      contents: read
      packages: write

    uses: davidbrownell/dbrownell_DevTools/.github/workflows/callable_create_docker_image.yaml@CI-v0.22.1
    with:
      operating_system: ubuntu-latest
      python_version: ${{ matrix.python_version }}
      name_suffix: -${{ matrix.python_version }}
      bootstrap_args: ""
      docker_description: "FileBackup - ${{ matrix.python_version }}"
      push_image_as_package: true
      container_registry_username: davidbrownell


  # ----------------------------------------------------------------------
  publish:
    needs:
      - validate_package
      - validate_binary
      - create_docker_image

    name: Publish

    permissions:
      contents: write

    uses: davidbrownell/dbrownell_DevTools/.github/workflows/callable_publish_python.yaml@CI-v0.22.1
    with:
      release_sources_configuration_filename: .github/release_sources.yaml
    secrets:
      PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
      MINISIGN_PRIVATE_KEY: ${{ secrets.MINISIGN_PRIVATE_KEY }}
